export const REMINDER_CONFIG = {
  CompCertRenew1: {
    code: 'CompCertRenew1',
    daysToExpiry: 150,
    submitDaysBeforeExpiry: 90,
    color: 'green',
    cardPillLabel: '',
    name: 'Renewal reminder: Competency certificate',
    text: 'Your competency certificate expires in {daysToExpiry} days',
    text2: 'You have {daysToSubmitApplication} days until you have to submit your application.',
  },
  CompCertRenew2: {
    code: 'CompCertRenew2',
    daysToExpiry: 120,
    submitDaysBeforeExpiry: 90,
    color: 'orange',
    cardPillLabel: 'Renew certificate',
    name: 'Renewal reminder: Competency certificate',
    text: 'Your competency certificate expires in {daysToExpiry} days',
    text2: 'You have {daysToSubmitApplication} days until you have to submit your application.',
  },
  CompCertRenew3: {
    code: 'CompCertRenew3',
    daysToExpiry: 90,
    submitDaysBeforeExpiry: 90,
    color: 'red',
    cardPillLabel: 'Renewal overdue',
    name: 'URGENT REMINDER: Competency certificate renewal',
    text: 'Your competency certificate expires in {daysToExpiry} days',
    text2: 'You have {daysToSubmitApplication} days until you have to submit your application.',
  },
  CompCertExp: {
    code: 'CompCertExp',
    daysToExpiry: 0,
    submitDaysBeforeExpiry: 90,
    color: 'red',
    cardPillLabel: 'EXPIRED',
    name: 'EXPIRED: Competency certificate',
    text: 'Your competency certificate expired on',
    text2: '',
  },

  FirearmRenew1: {
    code: 'FirearmRenew1',
    daysToExpiry: 150,
    submitDaysBeforeExpiry: 90,
    color: 'green',
    cardPillLabel: '',
    name: 'Renewal reminder: Firearm licence',
    text: 'Your firearm licence expires in {daysToExpiry} days',
    text2: 'You have {daysToSubmitApplication} days until you have to submit your application.',
  },
  FirearmRenew2: {
    code: 'FirearmRenew2',
    daysToExpiry: 120,
    submitDaysBeforeExpiry: 90,
    color: 'orange',
    cardPillLabel: 'Renew licence',
    name: 'Renewal reminder: Firearm licence',
    text: 'Your firearm licence expires in {daysToExpiry} days',
    text2: 'You have {daysToSubmitApplication} days until you have to submit your application.',
  },
  FirearmRenew3: {
    code: 'FirearmRenew3',
    daysToExpiry: 90,
    submitDaysBeforeExpiry: 90,
    color: 'red',
    cardPillLabel: 'Renewal overdue',
    name: 'URGENT REMINDER: Firearm licence renewal',
    text: 'Your firearm licence expires in {daysToExpiry} days',
    text2: 'You have {daysToSubmitApplication} days until you have to submit your application.',
  },
  FirearmExp: {
    code: 'FirearmExp',
    daysToExpiry: 0,
    submitDaysBeforeExpiry: 90,
    color: 'red',
    cardPillLabel: 'EXPIRED',
    name: 'EXPIRED: Firearm licence',
    text: 'Your firearm licence expired on',
    text2: '',
  },
  MembershipRenew1: {
    code: 'MembershipRenew1',
    daysToExpiry: 30,
    submitDaysBeforeExpiry: 0,
    color: 'orange',
    cardPillLabel: 'Renew membership',
    name: 'REMINDER: Membership',
    text: 'Your membership expires in {daysToExpiry} days',
    text2: '',
  },
  MembershipExp: {
    code: 'MembershipExp',
    daysToExpiry: 0,
    submitDaysBeforeExpiry: 0,
    color: 'red',
    cardPillLabel: 'EXPIRED',
    name: 'EXPIRED: Membership',
    text: 'Your membership expired on',
    text2: '',
  },
} as const;

export type ReminderCode = keyof typeof REMINDER_CONFIG;
export type ReminderConfig = (typeof REMINDER_CONFIG)[ReminderCode];
