type SharedRequirementDefaultsEntry = Record<string, unknown> & {
  displayOrderByForm?: Record<string, number>;
};
type SharedRequirementDefaults = Record<string, SharedRequirementDefaultsEntry>;

const imagePdfKinds = ['IMAGE', 'PDF'] as const;
const imagePdfMime = ['image/jpeg', 'image/png', 'application/pdf'] as const;

export const sharedRequirementDefaultsByCode: SharedRequirementDefaults = {
  ID_DOC: {
    label: 'Proof of identity',
    description: 'A South African ID card/book or passport. For an ID card, ensure both sides are uploaded.',
    checklistLabel: 'Two copies of a South African ID card (front and back), old ID book or passport.',
    helpKey: 'helpDocsId',
    documentKinds: [
      { kind: 'ID_CARD', numberOfSides: 2 },
      { kind: 'ID_BOOK', numberOfSides: 1 },
      { kind: 'PASSPORT', numberOfSides: 1 },
    ],
    copies: 2,
    min: 1,
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': true, '517g': true, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'A',
      '517g': 'C',
      '518a': 'E',
    },
    displayOrderByForm: {
      '517': 60,
      '517g': 20,
      '518a': 920,
    },
  },

  PROOF_ADDRESS: {
    label: 'Proof of address',
    description: 'Utility bill / bank statement / official letter showing name and current residential address.',
    checklistLabel: 'Proof of residential address not older than 3 months.',
    helpKey: 'helpDocsProofOfAddress',
    copies: 1,
    min: 1,
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'PROOF_OF_ADDRESS', numberOfSides: 1 }],
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': true, '517g': true, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'B',
      '517g': 'B',
      '518a': 'D',
    },
    displayOrderByForm: {
      '517': 61,
      '517g': 30,
      '518a': 921,
    },
  },
  
  PASSPORT_PHOTOS: {
    label: 'Passport photos',
    description: '2 standard passport photos. Full names and ID number written on the back of both.',
    checklistLabel: 'REQUIRED: Two passport photos with full names and ID number written on the back of both.',
    helpKey: 'helpDocsPassportPhotos',
    min: 2,
    max: 2,
    cardStyle: 'single',
    allowedKinds: ['IMAGE'],
    allowedMime: ['image/jpeg', 'image/png'],
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': false, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': false, '517g': false, '518a': false },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    displayOrderByForm: {
      '517': 72,
      '517g': 991,
      '518a': 41,
    },
  },

  MEMBERSHIP: {
    label: 'Membership',
    descriptionByForm: {
      '517': 'Optional firearm association membership documents related to the application.',
      '517g': 'Optional firearm association membership documents related to the application.',
      '518a': 'Firearm association membership documents related to the application.',
    },
    checklistLabel: 'Firearm association membership and dedicated status certificates.',
    helpKey: 'helpDocsMembership',
    cardStyle: 'multi',
    autoSelectSingle: false,
    allowMultipleUploads: true,
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': false, '517g': false, '518a': false },
    isChecklistItemByForm: { '517': false, '517g': false, '518a': false },
    requiredForApplicationByForm: {
      '517': false,
      '517g': false,
      '518a': true,
    },
    annexureByForm: {
      '517': 'H',
      '517g': 'G',
      '518a': 'H',
    },
    displayOrderByForm: {
      '517': 48,
      '517g': 15,
      '518a': 25,
    },
  },

  ASSOCIATION_MEMBERSHIP: {
    entityType: 'Membership',
    label: 'Association membership card (optional)',
    description: 'Membership card issued by a recognised firearm association, if your association provides one.',
    helpKey: 'helpDocsAssociationMembership',
    documentKinds: [{ kind: 'ASSOCIATION_MEMBERSHIP', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'H',
      '517g': 'G',
      '518a': 'H',
    },
    displayOrderByForm: {
      '517': 48.2,
      '517g': 16,
      '518a': 200,
    },
  },

  ASSOCIATION_LETTER: {
    entityType: 'Membership',
    label: 'Proof of current membership',
    description: 'A letter showing your membership expiry date and that fees are up to date.',
    helpKey: 'helpDocsAssociationLetter',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': true, '517g': true, '518a': true },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    documentKinds: [{ kind: 'ASSOCIATION_LETTER', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    annexureByForm: {
      '517': 'H',
      '517g': 'G',
      '518a': 'H',
    },
    displayOrderByForm: {
      '517': 48.1,
      '517g': 17,
      '518a': 235,
    },
  },

  DEDICATED_HUNTER_CERT: {
    entityType: 'Membership',
    label: 'Dedicated hunter certificate',
    description: 'Certificate from a hunting association confirming dedicated hunter status.',
    helpKey: 'helpDocsDedicatedHunter',
    documentKinds: [{ kind: 'DEDICATED_HUNTER_CERT', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': false, '517g': false, '518a': true },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'H',
      '517g': 'G',
      '518a': 'H',
    },
    displayOrderByForm: {
      '517': 48.3,
      '517g': 18,
      '518a': 220,
    },
  },

  DEDICATED_SPORT_CERT: {
    entityType: 'Membership',
    label: 'Dedicated sport shooter certificate',
    description: 'Certificate from a firearm association confirming dedicated sport shooter status.',
    helpKey: 'helpDocsDedicatedSport',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'DEDICATED_SPORT_CERT', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    requiredByForm: { '517': false, '517g': false, '518a': true },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'H',
      '517g': 'G',
      '518a': 'H',
    },
    displayOrderByForm: {
      '517': 48.4,
      '517g': 19,
      '518a': 230,
    },
  },

  FIREARM_ENDORSEMENT: {
    entityType: 'Membership',
    label: 'Firearm endorsement letter',
    description: 'Association endorsement letter specific to each selected firearm, confirming suitability for the selected purpose.',
    helpKey: 'helpDocsFirearmEndorsement',
    documentKinds: [{ kind: 'FIREARM_ENDORSEMENT', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    annexure: 'H',
    cardStyle: 'single',
    scope: { perFirearm: true },
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': false, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'H',
      '517g': 'G',
      '518a': 'H',
    },
    displayOrderByForm: {
      '517': 48.5,
      '517g': 19.5,
      '518a': 235,
    },
  },

  PROFICIENCY: {
    label: 'Proficiency',
    checklistLabelByForm: {
      '517': 'REQUIRED: Proficiency documents and related training results.',
      '517g': 'OPTIONAL: Proficiency documents.',
      '518a': 'OPTIONAL: Proficiency documents.',
    },
    descriptionByForm: {
      '517': 'Required proficiency document(s) related to this application.',
      '517g': 'Optional proficiency document(s) related to this application.',
      '518a': 'Optional proficiency document(s) related to this application.',
    },
    helpKey: 'helpDocsProficiency',
    cardStyle: 'multi',
    min: 1,
    max: 20,
    autoSelectSingle: false,
    allowMultipleUploads: true,
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    requiredByForm: { '517': true, '517g': false, '518a': false },
    requireUploadByForm: { '517': false, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': true, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': false, '517g': false, '518a': false },
    isChecklistItemByForm: { '517': false, '517g': false, '518a': false },
    annexureByForm: {
      '517': 'I',
      '517g': 'E',
      '518a': 'J',
    },
    displayOrderByForm: {
      '517': 47,
      '517g': 19.5,
      '518a': 28,
    },
  },

  PROFICIENCY_HANDGUN: {
    entityType: 'Proficiency',
    label: 'Handgun',
    description: 'Handgun proficiency document/training certificate.',
    helpKey: 'helpDocsProficiency',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'PROFICIENCY_HANDGUN', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'I',
      '517g': 'E',
      '518a': 'J',
    },
    displayOrderByForm: {
      '517': 47.1,
      '517g': 19.6,
      '518a': 241,
    },
  },

  PROFICIENCY_RIFLE: {
    entityType: 'Proficiency',
    label: 'Rifle',
    description: 'Rifle proficiency document/training certificate.',
    helpKey: 'helpDocsProficiency',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'PROFICIENCY_RIFLE', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'I',
      '517g': 'E',
      '518a': 'J',
    },
    displayOrderByForm: {
      '517': 47.2,
      '517g': 19.7,
      '518a': 242,
    },
  },

  PROFICIENCY_SHOTGUN: {
    entityType: 'Proficiency',
    label: 'Shotgun',
    description: 'Shotgun proficiency document/training certificate.',
    helpKey: 'helpDocsProficiency',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'PROFICIENCY_SHOTGUN', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'I',
      '517g': 'E',
      '518a': 'J',
    },
    displayOrderByForm: {
      '517': 47.3,
      '517g': 19.8,
      '518a': 243,
    },
  },

  PROFICIENCY_HANDMACHINECARBINE: {
    entityType: 'Proficiency',
    label: 'Hand machine carbine',
    description: 'Hand machine carbine proficiency document/training certificate.',
    helpKey: 'helpDocsProficiency',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'PROFICIENCY_HANDMACHINECARBINE', numberOfSides: 1 }],
    copies: 1,
    min: 1,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': true, '518a': true },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'I',
      '517g': 'E',
      '518a': 'J',
    },
    displayOrderByForm: {
      '517': 47.4,
      '517g': 19.9,
      '518a': 244,
    },
  },

  STATEMENT_OF_RESULTS: {
    label: 'PFTC/SASSETA results',
    description: 'Statement of results/certified copy, where available.',
    helpKey: 'helpDocsStatementOfResults',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'STATEMENT_OF_RESULTS', numberOfSides: 1 }],
    allowMultipleUploads: true,
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': false, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': false, '517g': false, '518a': false },
    isChecklistItemByForm: { '517': false, '517g': false, '518a': false },
    displayOrderByForm: {
      '517': 35,
    },
  },

  STATEMENT_OF_RESULTS_KNOWLEDGE: {
    entityType: 'Proficiency',
    label: 'Knowledge of the Firearms Control',
    description: 'Statement of results for knowledge of the Firearms Control Act.',
    helpKey: 'helpDocsStatementOfResults',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'STATEMENT_OF_RESULTS_KNOWLEDGE', numberOfSides: 1 }],
    allowMultipleUploads: false,
    requiredByForm: { '517': true, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': true, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    displayOrderByForm: { '517': 35.1 },
    annexureByForm: {
      '517': 'I',
      '517g': 'F',
      '518a': 'K',
    },
  },
  STATEMENT_OF_RESULTS_HANDLE_USE_1: {
    entityType: 'Proficiency',
    label: 'Handle and use results 1',
    description: 'Statement of results for handle and use module 1.',
    helpKey: 'helpDocsStatementOfResults',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'STATEMENT_OF_RESULTS_HANDLE_USE_1', numberOfSides: 1 }],
    allowMultipleUploads: false,
    requiredByForm: { '517': true, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    displayOrderByForm: { '517': 35.2 },
    annexureByForm: {
      '517': 'I',
      '517g': 'F',
      '518a': 'K',
    },
  },
  STATEMENT_OF_RESULTS_HANDLE_USE_2: {
    entityType: 'Proficiency',
    label: 'Handle and use results 2',
    description: 'Statement of results for handle and use module 2.',
    helpKey: 'helpDocsStatementOfResults',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'STATEMENT_OF_RESULTS_HANDLE_USE_2', numberOfSides: 1 }],
    allowMultipleUploads: false,
    requiredByForm: { '517': true, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    displayOrderByForm: { '517': 35.3 },
    annexureByForm: {
      '517': 'I',
      '517g': 'F',
      '518a': 'K',
    },
  },
  STATEMENT_OF_RESULTS_HANDLE_USE_3: {
    entityType: 'Proficiency',
    label: 'Handle and use results 3',
    description: 'Statement of results for handle and use module 3.',
    helpKey: 'helpDocsStatementOfResults',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'STATEMENT_OF_RESULTS_HANDLE_USE_3', numberOfSides: 1 }],
    allowMultipleUploads: false,
    requiredByForm: { '517': true, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    displayOrderByForm: { '517': 35.4 },
    annexureByForm: {
      '517': 'I',
      '517g': 'F',
      '518a': 'K',
    },
  },
  STATEMENT_OF_RESULTS_HANDLE_USE_4: {
    entityType: 'Proficiency',
    label: 'Handle and use results 4',
    description: 'Statement of results for handle and use module 4.',
    helpKey: 'helpDocsStatementOfResults',
    cardStyle: 'single',
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    documentKinds: [{ kind: 'STATEMENT_OF_RESULTS_HANDLE_USE_4', numberOfSides: 1 }],
    allowMultipleUploads: false,
    requiredByForm: { '517': true, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': false, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    displayOrderByForm: { '517': 35.5 },
    annexureByForm: {
      '517': 'I',
      '517g': 'F',
      '518a': 'K',
    },
  },

  SUPPORTING_STATEMENT_1: {
    label: 'Character reference',
    description: 'A character reference preferably from a spouse/family member.',
    checklistLabel: 'Character reference 1 (preferably from spouse/family member).',
    helpKey: 'helpDocSupportingStatement',
    documentKinds: [{ kind: 'SUPPORTING_STATEMENT', numberOfSides: 1 }],
    min: 0,
    max: 1,
    allowMultipleUploads: false,
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    cardStyle: 'single',
    requiredByForm: { '517': false, '517g': true, '518a': true },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': true, '517g': true, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'E',
      '517g': 'D',
      '518a': 'G',
    },
    displayOrderByForm: {
      '517': 50,
      '517g': 900,
      '518a': 900,
    },
  },

  SUPPORTING_STATEMENT_2: {
    label: 'Character reference',
    description: 'A character reference preferably from a friend/colleague/neighbour.',
    checklistLabel: 'Character reference 2 (preferably from a friend/colleague/neighbour).',
    helpKey: 'helpDocSupportingStatement',
    documentKinds: [{ kind: 'SUPPORTING_STATEMENT', numberOfSides: 1 }],
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    min: 0,
    max: 1,
    allowMultipleUploads: false,
    cardStyle: 'single',
    requiredByForm: { '517': false, '517g': true, '518a': true },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': true, '517g': true, '518a': true },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'E',
      '517g': 'D',
      '518a': 'G',
    },
    displayOrderByForm: {
      '517': 51,
      '517g': 901,
      '518a': 901,
    },
  },

  SUPPORTING_STATEMENT_3: {
    label: 'Character reference',
    description: 'Optional third character reference.',
    checklistLabel: 'Character reference 3 (check with DFO if needed).',
    helpKey: 'helpDocSupportingStatement',
    documentKinds: [{ kind: 'SUPPORTING_STATEMENT', numberOfSides: 1 }],
    min: 0,
    max: 1,
    allowMultipleUploads: false,
    allowedKinds: imagePdfKinds,
    allowedMime: imagePdfMime,
    cardStyle: 'single',
    requiredByForm: { '517': false, '517g': false, '518a': false },
    requireUploadByForm: { '517': true, '517g': false, '518a': false },
    requiredForApplicationByForm: { '517': true, '517g': false, '518a': false },
    isSupportingDocumentByForm: { '517': true, '517g': true, '518a': true },
    isChecklistItemByForm: { '517': true, '517g': true, '518a': true },
    annexureByForm: {
      '517': 'E',
      '517g': 'D',
      '518a': 'G',
    },
    displayOrderByForm: {
      '517': 52,
      '517g': 902,
      '518a': 902,
    },
  },
};
