import type { MotivationSentenceBank, SectionSentenceBank } from './sentenceBank.types';

const s16Sections: SectionSentenceBank[] = [
  {
    sectionId: 'S3',
    sectionKey: 'synopsisPurpose',
    templates: [
      {
        id: 's16.s3.core.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'This application is brought in terms of ${sectionTypeLabel} for ${purposeLabel}, and is supported by the applicant’s dedicated status and lawful participation in the relevant activities.',
        variables: ['sectionTypeLabel', 'purposeLabel'],
        evidence: [{ key: 'activity_participation', required: true, referenceStyle: 'grouped' }],
        tags: ['s16', 'purpose', 'dedicated'],
      },
      {
        id: 's16.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The purpose for which the firearm is required is specific, lawful, and directly connected to the applicant’s dedicated activities.',
        tags: ['s16', 'purpose', 'specific'],
      },
    ],
  },
  {
    sectionId: 'S4',
    sectionKey: 'experienceBackground',
    templates: [
      {
        id: 's16.s4.intro.001',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My background and experience with firearms are relevant to this application and are set out below.',
        tags: ['s16', 'experience'],
      },
      {
        id: 's16.s4.core.001',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I have accumulated practical experience in the lawful use, handling, and application of firearms over time, including experience relevant to the dedicated activities relied upon in this application.',
        tags: ['s16', 'experience', 'background'],
      },
      {
        id: 's16.s4.support.002',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${firearmExperienceSummary}',
        variables: ['firearmExperienceSummary'],
        conditions: [{ field: 'firearmExperienceSummary', operator: 'truthy' }],
        tags: ['s16', 'experience', 'history'],
      },
      {
        id: 's16.s4.support.003',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${ownershipHistorySummary}',
        variables: ['ownershipHistorySummary'],
        conditions: [{ field: 'ownershipHistorySummary', operator: 'truthy' }],
        tags: ['s16', 'experience', 'ownership'],
      },
    ],
  },
  {
    sectionId: 'S7',
    sectionKey: 'membershipStatus',
    templates: [
      {
        id: 's16.s7.intro.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'sectionIntro',
        strength: 'strong',
        text: 'My association membership and dedicated status are central to this application and are addressed below.',
        tags: ['s16', 'membership'],
      },
      {
        id: 's16.s7.core.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'I am a member in good standing of ${associationName}, and I hold the dedicated status relevant to this application.',
        variables: ['associationName'],
        conditions: [{ field: 'associationName', operator: 'truthy' }],
        evidence: [
          { key: 'association_membership', required: true, referenceStyle: 'grouped' },
          { key: 'dedicated_status', required: false, referenceStyle: 'grouped' },
        ],
        tags: ['s16', 'membership', 'dedicated'],
      },
      {
        id: 's16.s7.core.002',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'The application is further supported by the relevant endorsement issued in relation to the firearm and its intended dedicated use.',
        evidence: [{ key: 'firearm_endorsement', required: false, referenceStyle: 'grouped' }],
        tags: ['s16', 'membership', 'endorsement'],
      },
      {
        id: 's16.s7.support.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'My continued good standing and active participation within the association further support the bona fides of this application.',
        evidence: [{ key: 'activity_participation', required: true, referenceStyle: 'grouped' }],
        tags: ['s16', 'membership', 'standing'],
      },
      {
        id: 's16.s7.evidence.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The membership, dedicated-status, and endorsement material relevant to this application appears from ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [
          { key: 'association_membership', required: true, referenceStyle: 'grouped' },
          { key: 'dedicated_status', required: false, referenceStyle: 'grouped' },
          { key: 'firearm_endorsement', required: false, referenceStyle: 'grouped' },
        ],
        tags: ['s16', 'membership', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S8',
    sectionKey: 'existingFirearms',
    templates: [
      {
        id: 's16.s8.comparison.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'comparison',
        strength: 'veryStrong',
        text: 'Although I already own firearms, the firearms presently in my possession do not adequately meet the specific requirements of the dedicated use for which this application is brought.',
        conditions: [
          { field: 'requiresComparison', operator: 'truthy' },
          { field: 'inadequacySummary', operator: 'falsy' },
        ],
        tags: ['s16', 'existing-firearms', 'comparison'],
      },
      {
        id: 's16.s8.support.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'supportingClaim',
        strength: 'veryStrong',
        text: '${inadequacySummary}',
        variables: ['inadequacySummary'],
        conditions: [{ field: 'inadequacySummary', operator: 'truthy' }],
        evidence: [{ key: 'existing_licence_copy', required: false, referenceStyle: 'grouped' }],
        tags: ['s16', 'existing-firearms', 'gap'],
      },
    ],
  },
  {
    sectionId: 'S9',
    sectionKey: 'needJustification',
    templates: [
      {
        id: 's16.s9.core.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'I require the firearm applied for in order to participate properly, lawfully, and effectively in the dedicated activities relevant to this application.',
        tags: ['s16', 'need', 'dedicated'],
        conditions: [{ field: 'needSummary', operator: 'falsy' }],
      },
      {
        id: 's16.s9.core.002',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${needSummary}',
        variables: ['needSummary'],
        tags: ['s16', 'need', 'user-fact'],
      },
    ],
  },
  {
    sectionId: 'S10',
    sectionKey: 'suitabilityFit',
    templates: [
      {
        id: 's16.s10.core.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${firearmDescription} is suited to the dedicated purpose for which it is required and is an appropriate platform for that use.',
        variables: ['firearmDescription'],
        tags: ['s16', 'suitability', 'platform'],
        conditions: [{ field: 'suitabilitySummary', operator: 'falsy' }],
      },
      {
        id: 's16.s10.core.002',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${suitabilitySummary}',
        variables: ['suitabilitySummary'],
        tags: ['s16', 'suitability', 'user-fact'],
      },
      {
        id: 's16.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${capabilitySummary}',
        variables: ['capabilitySummary'],
        conditions: [{ field: 'capabilitySummary', operator: 'truthy' }],
        tags: ['s16', 'suitability', 'comparison', 'profile'],
      },
      {
        id: 's16.s10.support.002',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'Its design, action, calibre, and intended application make it a suitable and practical choice for the dedicated purpose described above.',
        conditions: [{ field: 'capabilitySummary', operator: 'falsy' }],
        tags: ['s16', 'suitability', 'comparison'],
      },
    ],
  },
  {
    sectionId: 'S11',
    sectionKey: 'activityUseDetail',
    templates: [
      {
        id: 's16.s11.intro.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'sectionIntro',
        strength: 'strong',
        text: 'My actual and intended dedicated activities are relevant to the present application and are summarised below.',
        tags: ['s16', 'activity'],
      },
      {
        id: 's16.s11.core.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${activitySummary}',
        variables: ['activitySummary'],
        conditions: [{ field: 'activitySummary', operator: 'truthy' }],
        tags: ['s16', 'activity', 'summary'],
      },
      {
        id: 's16.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${sportContextSummary}',
        variables: ['sportContextSummary'],
        conditions: [{ field: 'sportContextSummary', operator: 'truthy' }],
        tags: ['s16', 'activity', 'sport'],
      },
      {
        id: 's16.s11.support.002',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${huntingContextSummary}',
        variables: ['huntingContextSummary'],
        conditions: [{ field: 'huntingContextSummary', operator: 'truthy' }],
        tags: ['s16', 'activity', 'hunting'],
      },
      {
        id: 's16.s11.support.003',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${participationFrequencySummary}',
        variables: ['participationFrequencySummary'],
        conditions: [{ field: 'participationFrequencySummary', operator: 'truthy' }],
        tags: ['s16', 'activity', 'frequency'],
      },
      {
        id: 's16.s11.support.004',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${sportDisciplineSummary}',
        variables: ['sportDisciplineSummary'],
        conditions: [{ field: 'sportDisciplineSummary', operator: 'truthy' }],
        tags: ['s16', 'activity', 'discipline'],
      },
      {
        id: 's16.s11.support.005',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${huntingEnvironmentSummary}',
        variables: ['huntingEnvironmentSummary'],
        conditions: [{ field: 'huntingEnvironmentSummary', operator: 'truthy' }],
        tags: ['s16', 'activity', 'environment'],
      },
      {
        id: 's16.s11.evidence.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The applicant’s participation is further supported by the activity material attached at ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [{ key: 'activity_report', required: true, referenceStyle: 'grouped' }],
        tags: ['s16', 'activity', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S12',
    sectionKey: 'firearmCalibreContext',
    templates: [
      {
        id: 's16.s12.intro.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The technical characteristics of the firearm and calibre are relevant to its intended dedicated use.',
        tags: ['s16', 'technical'],
      },
      {
        id: 's16.s12.core.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'The combination of firearm type, action, and calibre is suitable for the specific dedicated purpose for which the firearm is sought.',
        tags: ['s16', 'technical', 'fit'],
      },
      {
        id: 's16.s12.support.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${illustrativeUseSummary}',
        variables: ['illustrativeUseSummary'],
        conditions: [{ field: 'illustrativeUseSummary', operator: 'truthy' }],
        tags: ['s16', 'technical', 'calibre', 'profile'],
      },
      {
        id: 's16.s12.support.002',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${capabilityLimitationSummary}',
        variables: ['capabilityLimitationSummary'],
        conditions: [{ field: 'capabilityLimitationSummary', operator: 'truthy' }],
        tags: ['s16', 'technical', 'limitation', 'profile'],
      },
      {
        id: 's16.s12.support.003',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'In the context of the applicant’s intended activities, the selected calibre and platform are appropriate and justified.',
        conditions: [
          { field: 'illustrativeUseSummary', operator: 'falsy' },
          { field: 'capabilityLimitationSummary', operator: 'falsy' },
        ],
        tags: ['s16', 'technical', 'calibre'],
      },
    ],
  },
  {
    sectionId: 'S15',
    sectionKey: 'conclusionRequest',
    templates: [
      {
        id: 's16.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'veryStrong',
        text: 'For all of the reasons set out above, I respectfully submit that this application meets the requirements applicable to ${sectionTypeLabel} and should be approved.',
        variables: ['sectionTypeLabel'],
        tags: ['s16', 'conclusion', 'approval'],
      },
      {
        id: 's16.s15.conclusion.002',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The application is supported by the applicant’s dedicated status, lawful participation, and the suitability of the firearm for the intended purpose.',
        tags: ['s16', 'conclusion', 'support'],
      },
    ],
  },
];

export const S16_SENTENCE_BANK: MotivationSentenceBank = {
  version: 'v1',
  sections: s16Sections,
};
