

import type {
  MotivationSentenceBank,
  OverlaySentenceBank,
  SectionSentenceBank,
} from './sentenceBank.types';

const sharedSections: SectionSentenceBank[] = [
  {
    sectionId: 'S1',
    sectionKey: 'titleSummary',
    templates: [
      {
        id: 'shared.s1.intro.001',
        sectionId: 'S1',
        sectionKey: 'titleSummary',
        kind: 'sectionIntro',
        strength: 'strong',
        text: 'MOTIVATION: ${applicationTypeLabel} IN TERMS OF ${sectionTypeLabel} FOR ${purposeLabel}.',
        variables: ['applicationTypeLabel', 'sectionTypeLabel', 'purposeLabel'],
        tags: ['shared', 'title', 'formal'],
      },
      {
        id: 'shared.s1.core.001',
        sectionId: 'S1',
        sectionKey: 'titleSummary',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'This motivation relates to the application concerning ${firearmDescription}, for the lawful purpose set out below.',
        variables: ['firearmDescription'],
        tags: ['shared', 'summary'],
      },
    ],
  },
  {
    sectionId: 'S2',
    sectionKey: 'applicantIdentity',
    templates: [
      {
        id: 'shared.s2.intro.001',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'I, ${applicantFullName}, respectfully submit this motivation in support of the present application.',
        variables: ['applicantFullName'],
        tags: ['shared', 'identity'],
      },
      {
        id: 'shared.s2.core.001',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I am a law-abiding and responsible person and I submit this application in good faith and for a lawful purpose.',
        tags: ['shared', 'identity', 'character'],
      },
      {
        id: 'shared.s2.support.001',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'supportingClaim',
        strength: 'standard',
        text: 'I am employed as ${occupation}, which reflects my stable personal circumstances and responsible standing.',
        variables: ['occupation'],
        conditions: [{ field: 'occupation', operator: 'truthy' }],
        tags: ['shared', 'identity', 'occupation'],
      },
      {
        id: 'shared.s2.support.0011',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'supportingClaim',
        strength: 'standard',
        text: 'I declare that the circumstances relating to the use of this firearm have not changed and that it is still used as originally motivated for.',
        tags: ['shared', 'identity', 'renewal', 'continuity'],
      },
      {
        id: 'shared.s2.support.0012',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'supportingClaim',
        strength: 'standard',
        text: 'I confirm that I have continued to comply with all requirements under which the firearm was originally licensed to me.',
        tags: ['shared', 'identity', 'renewal', 'compliance'],
      },
      {
        id: 'shared.s2.support.0013',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'supportingClaim',
        strength: 'standard',
        text: 'Since the licence was issued, I have adhered to the stipulations of the Firearms Control Act (FCA) and its regulations, and will continue to do so.',
        tags: ['shared', 'identity', 'renewal', 'fca'],
      },
      {
        id: 'shared.s2.support.002',
        sectionId: 'S2',
        sectionKey: 'applicantIdentity',
        kind: 'supportingClaim',
        strength: 'standard',
        text: 'In support of this application, character references are included as independent references. These statements confirm my good character, responsible conduct, and fitness to possess and use firearms lawfully.',
        tags: ['shared', 'identity', 'supporting-statements'],
      },
    ],
  },
  {
    sectionId: 'S3',
    sectionKey: 'synopsisPurpose',
    templates: [
      {
        id: 'shared.s3.intro.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'sectionIntro',
        strength: 'strong',
        text: 'The purpose of this application is clear and lawful, and is summarised as follows.',
        tags: ['shared', 'purpose'],
      },
      {
        id: 'shared.s3.core.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'The firearm is required for ${primaryUse}, and will be used in the manner described in this motivation.',
        variables: ['primaryUse'],
        tags: ['shared', 'purpose'],
      },
      {
        id: 'shared.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${useSummary}',
        variables: ['useSummary'],
        tags: ['shared', 'purpose', 'user-fact'],
      },
    ],
  },
  {
    sectionId: 'S5',
    sectionKey: 'trainingProficiency',
    templates: [
      {
        id: 'shared.s5.intro.001',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My training and proficiency in the lawful handling and use of firearms are set out below.',
        tags: ['shared', 'training'],
      },
      {
        id: 'shared.s5.core.001',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I have successfully completed the relevant proficiency training required by the Firearm Control Act for the lawful possession and use of firearms, including proficiency for ${proficiencyCategories}.',
        variables: ['proficiencyCategories'],
        conditions: [{ field: 'proficiencyCategories', operator: 'truthy' }],
        evidence: [
          { key: 'proficiency_certificate', required: true, referenceStyle: 'grouped' },
        ],
        tags: ['shared', 'training', 'proficiency'],
      },
      {
        id: 'shared.s5.core.002',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I have successfully completed the relevant proficiency training required by the Firearm Control Act for the lawful possession and use of firearms.',
        conditions: [{ field: 'proficiencyCategories', operator: 'falsy' }],
        evidence: [
          { key: 'proficiency_certificate', required: true, referenceStyle: 'grouped' },
        ],
        tags: ['shared', 'training', 'proficiency'],
      },
      {
        id: 'shared.s5.support.001',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'supportingClaim',
        strength: 'standard',
        text: 'My training was completed through ${trainingProviderName}.',
        variables: ['trainingProviderName'],
        conditions: [{ field: 'trainingProviderName', operator: 'truthy' }],
        tags: ['shared', 'training', 'provider'],
      },
      {
        id: 'shared.s5.evidence.001',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The relevant proficiency documentation is attached at ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [{ key: 'proficiency_certificate', required: true, referenceStyle: 'grouped' }],
        tags: ['shared', 'training', 'evidence'],
      },
      {
        id: 'shared.s5.sor.001',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'I have attached the Statement of Results documentation achieved for ${statementOfResultsItems}.',
        variables: ['statementOfResultsItems'],
        conditions: [{ field: 'statementOfResultsItems', operator: 'truthy' }],
        evidence: [{ key: 'statement_of_results', required: true, referenceStyle: 'grouped' }],
        tags: ['shared', 'training', 'statement-of-results'],
      },
      {
        id: 'shared.s5.sor.002',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The relevant Statement of Results documentation is attached at ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [{ key: 'statement_of_results', required: true, referenceStyle: 'grouped' }],
        tags: ['shared', 'training', 'statement-of-results', 'evidence'],
      },
      {
        id: 'shared.s5.endorsement.001',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'In respect of the ${firearmShortDescription}, the endorsement records that the motivation has technical merit and that the firearm is suitable for the purpose for which the licence is sought.',
        variables: ['firearmShortDescription'],
        conditions: [{ field: 'hasRelevantFirearmEndorsement', operator: 'truthy' }],
        evidence: [{ key: 'firearm_endorsement', required: true, referenceStyle: 'grouped' }],
        tags: ['shared', 'training', 'endorsement'],
      },
      {
        id: 'shared.s5.endorsement.002',
        sectionId: 'S5',
        sectionKey: 'trainingProficiency',
        kind: 'evidenceLink',
        strength: 'standard',
        text: 'The endorsement supporting the ${firearmShortDescription} is reflected in ${annexureReferenceGrouped}.',
        variables: ['firearmShortDescription', 'annexureReferenceGrouped'],
        conditions: [{ field: 'hasRelevantFirearmEndorsement', operator: 'truthy' }],
        evidence: [{ key: 'firearm_endorsement', required: true, referenceStyle: 'grouped' }],
        tags: ['shared', 'training', 'endorsement', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S6',
    sectionKey: 'competency',
    templates: [
      {
        id: 'shared.s6.intro.001',
        sectionId: 'S6',
        sectionKey: 'competency',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My competency status in relation to the relevant firearm categories is set out below.',
        tags: ['shared', 'competency'],
      },
      {
        id: 'shared.s6.core.001',
        sectionId: 'S6',
        sectionKey: 'competency',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'I have been declared competent in respect of the relevant firearm categories and remain legally competent for the purposes of this application.',
        evidence: [
          { key: 'competency_certificate', required: true, referenceStyle: 'grouped' },
        ],
        tags: ['shared', 'competency', 'critical'],
      },
      {
        id: 'shared.s6.support.001',
        sectionId: 'S6',
        sectionKey: 'competency',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'My competency covers the following relevant categories: ${competencyCategories}.',
        variables: ['competencyCategories'],
        conditions: [{ field: 'competencyCategories', operator: 'truthy' }],
        tags: ['shared', 'competency', 'categories'],
      },
      {
        id: 'shared.s6.evidence.001',
        sectionId: 'S6',
        sectionKey: 'competency',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'My competency documentation appears from ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [
          { key: 'competency_certificate', required: true, referenceStyle: 'grouped' },
        ],
        tags: ['shared', 'competency', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S8',
    sectionKey: 'existingFirearms',
    templates: [
      {
        id: 'shared.s8.intro.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My current firearms are relevant to the present application and are addressed for purposes of context and comparison.',
        conditions: [{ field: 'requiresComparison', operator: 'truthy' }],
        tags: ['shared', 'existing-firearms'],
      },
      {
        id: 'shared.s8.intro.002',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The existing-firearms position relevant to this application is set out below.',
        conditions: [{ field: 'requiresComparison', operator: 'falsy' }],
        tags: ['shared', 'existing-firearms'],
      },
      {
        id: 'shared.s8.comparison.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'comparison',
        strength: 'strong',
        text: 'Although I already own firearms, none of them adequately serve the purpose of the present application for the reasons set out below.',
        conditions: [{ field: 'requiresComparison', operator: 'truthy' }],
        tags: ['shared', 'existing-firearms', 'comparison'],
      },
      {
        id: 'shared.s8.core.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I confirm that I do not own any other firearms.',
        conditions: [{ field: 'requiresComparison', operator: 'falsy' }],
        tags: ['shared', 'existing-firearms', 'comparison'],
      },
      {
        id: 'shared.s8.support.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${inadequacySummary}',
        variables: ['inadequacySummary'],
        conditions: [{ field: 'inadequacySummary', operator: 'truthy' }],
        tags: ['shared', 'existing-firearms', 'gap'],
      },
      {
        id: 'shared.s8.evidence.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The licence documentation relating to the applicant’s existing firearm appears from ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [{ key: 'existing_licence_copy', required: true, referenceStyle: 'grouped' }],
        conditions: [{ field: 'requiresComparison', operator: 'truthy' }],
        tags: ['shared', 'existing-firearms', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S9',
    sectionKey: 'needJustification',
    templates: [
      {
        id: 'shared.s9.intro.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'sectionIntro',
        strength: 'strong',
        text: 'The need for the firearm is genuine, lawful, and properly grounded in fact.',
        tags: ['shared', 'need'],
      },
      {
        id: 'shared.s9.core.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${needSummary}',
        variables: ['needSummary'],
        conditions: [{ field: 'needSummary', operator: 'truthy' }],
        tags: ['shared', 'need', 'user-fact'],
      },
      {
        id: 'shared.s9.support.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${primaryNeedSummary}',
        variables: ['primaryNeedSummary'],
        conditions: [{ field: 'primaryNeedSummary', operator: 'truthy' }],
        tags: ['shared', 'need', 'user-fact'],
      },
      {
        id: 'shared.s9.support.002',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'standard',
        text: '${needNoteSummary}',
        variables: ['needNoteSummary'],
        conditions: [{ field: 'needNoteSummary', operator: 'truthy' }],
        tags: ['shared', 'need', 'user-fact'],
      },
    ],
  },
  {
    sectionId: 'S10',
    sectionKey: 'suitabilityFit',
    templates: [
      {
        id: 'shared.s10.intro.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The firearm applied for is suitable for the intended lawful purpose for the reasons set out below.',
        tags: ['shared', 'suitability'],
      },
      {
        id: 'shared.s10.core.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${suitabilitySummary}',
        variables: ['suitabilitySummary'],
        tags: ['shared', 'suitability', 'user-fact'],
      },
      {
        id: 'shared.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The characteristics of ${firearmDescription} make it appropriate for the intended use described in this application.',
        variables: ['firearmDescription'],
        tags: ['shared', 'suitability', 'firearm'],
      },
    ],
  },
  {
    sectionId: 'S13',
    sectionKey: 'safeStorage',
    templates: [
      {
        id: 'shared.s13.intro.001',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The safe-storage arrangements applicable to this application are set out below.',
        tags: ['shared', 'storage'],
      },
      {
        id: 'shared.s13.core.001',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'The firearm will be stored in a compliant safe and kept under secure conditions when not in use.',
        evidence: [{ key: 'safe_photos', required: false, referenceStyle: 'grouped' }],
        tags: ['shared', 'storage', 'critical'],
      },
      {
        id: 'shared.s13.support.001',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${homeTypeSummary}',
        variables: ['homeTypeSummary'],
        conditions: [{ field: 'homeTypeSummary', operator: 'truthy' }],
        tags: ['shared', 'storage', 'security'],
      },
      {
        id: 'shared.s13.support.002',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${homeSecurityIntro}',
        variables: ['homeSecurityIntro'],
        conditions: [{ field: 'homeSecurityIntro', operator: 'truthy' }],
        tags: ['shared', 'storage', 'security'],
      },
      {
        id: 'shared.s13.support.003',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${homeSecurityMeasureSummary}',
        variables: ['homeSecurityMeasureSummary'],
        conditions: [{ field: 'homeSecurityMeasureSummary', operator: 'truthy' }],
        tags: ['shared', 'storage', 'security'],
      },
      {
        id: 'shared.s13.support.004',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${residenceSecuritySummary}',
        variables: ['residenceSecuritySummary'],
        conditions: [{ field: 'residenceSecuritySummary', operator: 'truthy' }],
        tags: ['shared', 'storage', 'security'],
      },
      {
        id: 'shared.s13.support.005',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${safeDescription}',
        variables: ['safeDescription'],
        conditions: [{ field: 'safeDescription', operator: 'truthy' }],
        tags: ['shared', 'storage', 'safe'],
      },
      {
        id: 'shared.s13.evidence.001',
        sectionId: 'S13',
        sectionKey: 'safeStorage',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'Photographic proof of the storage arrangements is attached at ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        evidence: [{ key: 'safe_photos', required: true, referenceStyle: 'grouped' }],
        tags: ['shared', 'storage', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S14',
    sectionKey: 'legalFraming',
    templates: [
      {
        id: 'shared.s14.intro.001',
        sectionId: 'S14',
        sectionKey: 'legalFraming',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'This application is made within the framework of the Firearms Control Act and the applicable requirements arising therefrom.',
        tags: ['shared', 'legal'],
      },
      {
        id: 'shared.s14.core.001',
        sectionId: 'S14',
        sectionKey: 'legalFraming',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I submit that this application complies with the applicable statutory requirements and is supported by the accompanying evidence.',
        tags: ['shared', 'legal', 'compliance'],
      },
      {
        id: 'shared.s14.support.001',
        sectionId: 'S14',
        sectionKey: 'legalFraming',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'Section 25 of the Constitution provides, among other things, that "no one may be deprived of property except in terms of a law of general application, and no law may permit arbitrary deprivation of property." I am advised that refusal of this application would amount to a deprivation of property that does not fall within the acceptable legal provisions contemplated in the Constitution, as applicable to the licensing of this firearm.',
        tags: ['shared', 'legal', 'renewal', 'constitutional'],
      },
      {
        id: 'shared.s14.evidence.001',
        sectionId: 'S14',
        sectionKey: 'legalFraming',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The supporting documentation relied upon in this application appears from ${annexureReferenceGrouped}.',
        variables: ['annexureReferenceGrouped'],
        tags: ['shared', 'legal', 'evidence'],
      },
    ],
  },
  {
    sectionId: 'S15',
    sectionKey: 'conclusionRequest',
    templates: [
      {
        id: 'shared.s15.intro.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'In conclusion, I respectfully submit the following.',
        tags: ['shared', 'conclusion'],
      },
      {
        id: 'shared.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'veryStrong',
        text: 'In the circumstances, I respectfully request that the application be approved.',
        tags: ['shared', 'conclusion', 'request'],
      },
      {
        id: 'shared.s15.conclusion.002',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'I accordingly request that the relevant licence be granted or renewed, as the case may be.',
        tags: ['shared', 'conclusion', 'request'],
      },
    ],
  },
  {
    sectionId: 'S16',
    sectionKey: 'annexures',
    templates: [
      {
        id: 'shared.s16.intro.001',
        sectionId: 'S16',
        sectionKey: 'annexures',
        kind: 'annexureLeadIn',
        strength: 'standard',
        text: 'The supporting documents attached to this motivation are listed below.',
        tags: ['shared', 'annexures'],
      },
      {
        id: 'shared.s16.evidence.001',
        sectionId: 'S16',
        sectionKey: 'annexures',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The annexure references used in this motivation correspond with the supporting documents identified above.',
        tags: ['shared', 'annexures', 'evidence'],
      },
    ],
  },
];

const sharedOverlays: OverlaySentenceBank[] = [
  {
    overlay: 'base',
    templates: [
      {
        id: 'shared.overlay.base.transition.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'transition',
        strength: 'standard',
        text: 'Against that background, I set out below the facts relevant to this application.',
        tags: ['shared', 'overlay', 'base', 'transition'],
      },
      {
        id: 'shared.overlay.base.evidence.001',
        sectionId: 'S16',
        sectionKey: 'annexures',
        kind: 'evidenceLink',
        strength: 'strong',
        text: 'The statements made in this motivation are, where applicable, supported by the annexures identified above.',
        tags: ['shared', 'overlay', 'base', 'evidence'],
      },
    ],
  },
  {
    overlay: 'renewal',
    templates: [
      {
        id: 'shared.overlay.renewal.core.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${continuedNeedSummary}',
        variables: ['continuedNeedSummary'],
        conditions: [{ field: 'continuedNeedSummary', operator: 'truthy' }],
        tags: ['shared', 'overlay', 'renewal', 'need'],
      },
      {
        id: 'shared.overlay.renewal.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The firearm remains suitable for the purpose for which it is licensed and continues to be required for that lawful purpose.',
        tags: ['shared', 'overlay', 'renewal', 'conclusion'],
      },
    ],
  },
];

export const SHARED_SENTENCE_BANK: MotivationSentenceBank = {
  version: 'v1',
  sections: sharedSections,
  overlays: sharedOverlays,
};
