

import type { MotivationSentenceBank, OverlaySentenceBank } from './sentenceBank.types';

const overlays: OverlaySentenceBank[] = [
  {
    overlay: 'selfDefence',
    templates: [
      {
        id: 'overlay.selfDefence.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The purpose of this application must be considered against the practical realities of personal safety and the applicant’s need for lawful protection.',
        tags: ['overlay', 'selfDefence', 'purpose'],
      },
      {
        id: 'overlay.selfDefence.s9.support.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'veryStrong',
        text: 'The applicant’s need for self-defence is rooted in real-world safety concerns and must be assessed in the context of prevailing violent crime conditions.',
        tags: ['overlay', 'selfDefence', 'need', 'crime-context'],
      },
      {
        id: 'overlay.selfDefence.s9.support.002',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'In assessing this application, regard should be given not only to the applicant’s personal circumstances, but also to the broader criminal environment within which the applicant lives, works, and travels.',
        tags: ['overlay', 'selfDefence', 'need', 'context'],
      },
      {
        id: 'overlay.selfDefence.s9.support.003',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'veryStrong',
        text: '${crimeStatsSummary}',
        variables: ['crimeStatsSummary'],
        conditions: [{ field: 'crimeStatsSummary', operator: 'truthy' }],
        tags: ['overlay', 'selfDefence', 'need', 'fact-bank'],
      },
      {
        id: 'overlay.selfDefence.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'A firearm suitable for self-defence must be capable of lawful defensive use in urgent circumstances where delay may expose the applicant to serious harm.',
        tags: ['overlay', 'selfDefence', 'suitability'],
      },
      {
        id: 'overlay.selfDefence.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The firearm will be possessed and used solely for lawful self-defence and will remain subject to responsible storage, handling, and control at all times.',
        tags: ['overlay', 'selfDefence', 'use'],
      },
      {
        id: 'overlay.selfDefence.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'In the premises, the applicant respectfully submits that the licence sought is justified as a reasonable and lawful measure of personal protection.',
        tags: ['overlay', 'selfDefence', 'conclusion'],
      },
    ],
  },
  {
    overlay: 'hunting',
    templates: [
      {
        id: 'overlay.hunting.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The application must be understood in the context of the applicant’s intended hunting activities and the practical demands associated with those activities.',
        tags: ['overlay', 'hunting', 'purpose'],
      },
      {
        id: 'overlay.hunting.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'In the hunting context, the selected firearm must be assessed with reference to suitability for the intended game, terrain, range profile, and humane effectiveness.',
        tags: ['overlay', 'hunting', 'suitability'],
      },
      {
        id: 'overlay.hunting.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${huntingContextSummary}',
        variables: ['huntingContextSummary'],
        conditions: [{ field: 'huntingContextSummary', operator: 'truthy' }],
        tags: ['overlay', 'hunting', 'activity'],
      },
      {
        id: 'overlay.hunting.s11.support.002',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The applicant intends to use the firearm in a hunting context and for purposes consistent with responsible and ethical firearm use.',
        tags: ['overlay', 'hunting', 'activity'],
      },
      {
        id: 'overlay.hunting.s12.support.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The selected calibre and platform should be considered in light of practical hunting suitability rather than in abstraction.',
        tags: ['overlay', 'hunting', 'technical'],
      },
      {
        id: 'overlay.hunting.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The applicant accordingly submits that the firearm is justified for hunting use and that the application should be approved.',
        tags: ['overlay', 'hunting', 'conclusion'],
      },
    ],
  },
  {
    overlay: 'sportShooting',
    templates: [
      {
        id: 'overlay.sportShooting.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The application must be evaluated with reference to the applicant’s intended participation in sport shooting activities and the requirements of those activities.',
        tags: ['overlay', 'sportShooting', 'purpose'],
      },
      {
        id: 'overlay.sportShooting.s7.support.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The applicant’s membership and participation in the relevant sport shooting structures support the bona fides of the application.',
        tags: ['overlay', 'sportShooting', 'membership'],
      },
      {
        id: 'overlay.sportShooting.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'Suitability in the sport shooting context must be assessed with reference to platform, action type, discipline demands, and practical performance requirements.',
        tags: ['overlay', 'sportShooting', 'suitability'],
      },
      {
        id: 'overlay.sportShooting.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${sportContextSummary}',
        variables: ['sportContextSummary'],
        conditions: [{ field: 'sportContextSummary', operator: 'truthy' }],
        tags: ['overlay', 'sportShooting', 'activity'],
      },
      {
        id: 'overlay.sportShooting.s11.support.002',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The applicant intends to use the firearm in sport shooting activities, training, and participation consistent with the purpose set out in this application.',
        tags: ['overlay', 'sportShooting', 'activity'],
      },
      {
        id: 'overlay.sportShooting.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The applicant accordingly submits that the firearm is justified for sport shooting use and that the application should be approved.',
        tags: ['overlay', 'sportShooting', 'conclusion'],
      },
    ],
  },
  {
    overlay: 'mixedHuntingSport',
    templates: [
      {
        id: 'overlay.mixed.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'This application should be considered in the context of both hunting and sport shooting requirements where the applicant relies on both lawful use cases.',
        tags: ['overlay', 'mixedHuntingSport', 'purpose'],
      },
      {
        id: 'overlay.mixed.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The firearm is suitable in that it can lawfully and practically serve the applicant’s combined hunting and sport shooting requirements.',
        tags: ['overlay', 'mixedHuntingSport', 'suitability'],
      },
      {
        id: 'overlay.mixed.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${huntingContextSummary}',
        variables: ['huntingContextSummary'],
        conditions: [{ field: 'huntingContextSummary', operator: 'truthy' }],
        tags: ['overlay', 'mixedHuntingSport', 'activity', 'hunting'],
      },
      {
        id: 'overlay.mixed.s11.support.002',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${sportContextSummary}',
        variables: ['sportContextSummary'],
        conditions: [{ field: 'sportContextSummary', operator: 'truthy' }],
        tags: ['overlay', 'mixedHuntingSport', 'activity', 'sport'],
      },
      {
        id: 'overlay.mixed.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The applicant accordingly submits that the firearm is justified for the combined lawful purposes set out above and that the application should be approved.',
        tags: ['overlay', 'mixedHuntingSport', 'conclusion'],
      },
    ],
  },
];

export const OVERLAY_SENTENCE_BANK: MotivationSentenceBank = {
  version: 'v1',
  sections: [],
  overlays,
};
