import type { MotivationSentenceBank, SectionSentenceBank } from './sentenceBank.types';

const s13Sections: SectionSentenceBank[] = [
  {
    sectionId: 'S3',
    sectionKey: 'synopsisPurpose',
    templates: [
      {
        id: 's13.s3.core.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'This application is brought in terms of ${sectionTypeLabel} for the purpose of self-defence, and is based on a genuine and lawful need for personal protection.',
        variables: ['sectionTypeLabel'],
        tags: ['s13', 'purpose', 'self-defence'],
      },
      {
        id: 's13.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The need for self-defence arises from the applicant’s circumstances and the broader security environment within which the applicant lives and operates.',
        tags: ['s13', 'purpose', 'context'],
      },
    ],
  },
  {
    sectionId: 'S9',
    sectionKey: 'needJustification',
    templates: [
      {
        id: 's13.s9.core.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'I require a firearm for the purpose of self-defence due to a real and ongoing risk to my personal safety.',
        tags: ['s13', 'need', 'risk'],
        conditions: [{ field: 'needSummary', operator: 'falsy' }],
      },
      {
        id: 's13.s9.core.002',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${needSummary}',
        variables: ['needSummary'],
        tags: ['s13', 'need', 'user-fact'],
      },
      {
        id: 's13.s9.support.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'veryStrong',
        text: '${selfDefenceContextSummary}',
        variables: ['selfDefenceContextSummary'],
        conditions: [{ field: 'selfDefenceContextSummary', operator: 'truthy' }],
        tags: ['s13', 'need', 'context'],
      },
      {
        id: 's13.s9.support.003',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'veryStrong',
        text: '${crimeStatsSummary}',
        variables: ['crimeStatsSummary'],
        conditions: [{ field: 'crimeStatsSummary', operator: 'truthy' }],
        tags: ['s13', 'need', 'fact-bank'],
      },
      {
        id: 's13.s9.support.004',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${ownershipHistorySummary}',
        variables: ['ownershipHistorySummary'],
        conditions: [{ field: 'ownershipHistorySummary', operator: 'truthy' }],
        tags: ['s13', 'need', 'history'],
      },
    ],
  },
  {
    sectionId: 'S10',
    sectionKey: 'suitabilityFit',
    templates: [
      {
        id: 's13.s10.core.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${firearmDescription} is suitable for self-defence and is an appropriate firearm for lawful personal protection.',
        variables: ['firearmDescription'],
        tags: ['s13', 'suitability'],
        conditions: [{ field: 'suitabilitySummary', operator: 'falsy' }],
      },
      {
        id: 's13.s10.core.002',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${suitabilitySummary}',
        variables: ['suitabilitySummary'],
        tags: ['s13', 'suitability', 'user-fact'],
      },
      {
        id: 's13.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${capabilitySummary}',
        variables: ['capabilitySummary'],
        conditions: [{ field: 'capabilitySummary', operator: 'truthy' }],
        tags: ['s13', 'suitability', 'defence', 'profile'],
      },
      {
        id: 's13.s10.support.002',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The firearm provides the applicant with a reasonable and lawful means of protection in circumstances where immediate defensive action may be required.',
        conditions: [{ field: 'capabilitySummary', operator: 'falsy' }],
        tags: ['s13', 'suitability', 'defence'],
      },
    ],
  },
  {
    sectionId: 'S11',
    sectionKey: 'activityUseDetail',
    templates: [
      {
        id: 's13.s11.intro.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The manner in which the firearm will be used is relevant to this application and is set out below.',
        tags: ['s13', 'use'],
      },
      {
        id: 's13.s11.core.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'The firearm will be used strictly for lawful self-defence and will not be used for any unlawful purpose.',
        tags: ['s13', 'use', 'lawful'],
      },
      {
        id: 's13.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The firearm will be carried and controlled responsibly, and used only where lawful self-defence makes such use necessary.',
        tags: ['s13', 'use', 'responsible'],
      },
      {
        id: 's13.s11.support.002',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${participationFrequencySummary}',
        variables: ['participationFrequencySummary'],
        conditions: [{ field: 'participationFrequencySummary', operator: 'truthy' }],
        tags: ['s13', 'use', 'preparedness'],
      },
    ],
  },
  {
    sectionId: 'S12',
    sectionKey: 'firearmCalibreContext',
    templates: [
      {
        id: 's13.s12.intro.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The technical characteristics of the firearm, calibre, and sighting setup are relevant to lawful self-defence use.',
        tags: ['s13', 'technical'],
      },
      {
        id: 's13.s12.core.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'coreClaim',
        strength: 'strong',
        text: '${firearmDescription} is technically suited to lawful self-defence use, with practical regard to platform, calibre, and controllable operation.',
        variables: ['firearmDescription'],
        tags: ['s13', 'technical', 'fit'],
      },
      {
        id: 's13.s12.support.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'Where selected, the ${sightingSystemLabel} supports safe and practical alignment in lawful defensive use.',
        variables: ['sightingSystemLabel'],
        conditions: [{ field: 'sightingSystemLabel', operator: 'truthy' }],
        tags: ['s13', 'technical', 'sighting'],
      },
    ],
  },
  {
    sectionId: 'S15',
    sectionKey: 'conclusionRequest',
    templates: [
      {
        id: 's13.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'veryStrong',
        text: 'In light of the above, I respectfully submit that the application is justified and that the licence should be granted.',
        tags: ['s13', 'conclusion'],
      },
      {
        id: 's13.s15.conclusion.002',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The application is supported by the applicant’s personal circumstances, the self-defence need set out above, and the suitability of the firearm for lawful personal protection.',
        tags: ['s13', 'conclusion', 'support'],
      },
    ],
  },
];

export const S13_SENTENCE_BANK: MotivationSentenceBank = {
  version: 'v1',
  sections: s13Sections,
};
