import type { MotivationSentenceBank, SectionSentenceBank } from './sentenceBank.types';

const s15Sections: SectionSentenceBank[] = [
  {
    sectionId: 'S3',
    sectionKey: 'synopsisPurpose',
    templates: [
      {
        id: 's15.s3.core.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'This application is submitted in terms of ${sectionTypeLabel} for occasional ${primaryUse}.',
        variables: ['sectionTypeLabel', 'primaryUse'],
        tags: ['s15', 'purpose', 'lawful'],
      },
      {
        id: 's15.s3.core.002',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'The firearm is required for legitimate and practical use as detailed in this motivation.',
        tags: ['s15', 'purpose', 'lawful'],
      },
      {
        id: 's15.s3.support.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'The intended use is genuine, specific, and consistent with the provisions governing occasional hunting and/or sport shooting.',
        tags: ['s15', 'purpose', 'occasional'],
      },
      {
        id: 's15.s3.conclusion.001',
        sectionId: 'S3',
        sectionKey: 'synopsisPurpose',
        kind: 'conclusion',
        strength: 'strong',
        text: 'This application should therefore be considered with reference to the applicable use case or use cases on which the applicant relies.',
        tags: ['s15', 'purpose', 'occasional'],
      },
    ],
  },
  {
    sectionId: 'S4',
    sectionKey: 'experienceBackground',
    templates: [
      {
        id: 's15.s4.intro.001',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My background and experience with firearms are relevant to this application and are addressed below.',
        tags: ['s15', 'experience'],
      },
      {
        id: 's15.s4.core.001',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I have acquired practical experience in the lawful handling, use, and application of firearms over time, including experience relevant to the purpose relied upon in this application.',
        tags: ['s15', 'experience', 'background'],
      },
      {
        id: 's15.s4.support.002',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${firearmExperienceSummary}',
        variables: ['firearmExperienceSummary'],
        conditions: [{ field: 'firearmExperienceSummary', operator: 'truthy' }],
        tags: ['s15', 'experience', 'history'],
      },
      {
        id: 's15.s4.support.003',
        sectionId: 'S4',
        sectionKey: 'experienceBackground',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${ownershipHistorySummary}',
        variables: ['ownershipHistorySummary'],
        conditions: [{ field: 'ownershipHistorySummary', operator: 'truthy' }],
        tags: ['s15', 'experience', 'ownership'],
      },
    ],
  },
  {
    sectionId: 'S7',
    sectionKey: 'membershipStatus',
    templates: [
      {
        id: 's15.s7.intro.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My association membership and related status, where applicable, are addressed below.',
        tags: ['s15', 'membership'],
      },
      {
        id: 's15.s7.core.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'I am a member of ${associationName}, and such membership supports the bona fides of this application.',
        variables: ['associationName'],
        conditions: [{ field: 'associationName', operator: 'truthy' }],
        evidence: [{ key: 'association_membership', required: false, referenceStyle: 'grouped' }],
        tags: ['s15', 'membership', 'association'],
      },
      {
        id: 's15.s7.support.001',
        sectionId: 'S7',
        sectionKey: 'membershipStatus',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'Although dedicated status is not the basis of this application, the applicant’s association involvement remains relevant to lawful and responsible firearm use.',
        tags: ['s15', 'membership', 'context'],
      },
    ],
  },
  {
    sectionId: 'S8',
    sectionKey: 'existingFirearms',
    templates: [
      {
        id: 's15.s8.comparison.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'comparison',
        strength: 'veryStrong',
        text: 'Although I already own firearms, the firearms presently in my possession do not adequately serve the practical purpose for which this application is made.',
        conditions: [
          { field: 'requiresComparison', operator: 'truthy' },
          { field: 'inadequacySummary', operator: 'falsy' },
        ],
        tags: ['s15', 'existing-firearms', 'comparison'],
      },
      {
        id: 's15.s8.support.001',
        sectionId: 'S8',
        sectionKey: 'existingFirearms',
        kind: 'supportingClaim',
        strength: 'veryStrong',
        text: '${inadequacySummary}',
        variables: ['inadequacySummary'],
        conditions: [{ field: 'inadequacySummary', operator: 'truthy' }],
        evidence: [{ key: 'existing_licence_copy', required: false, referenceStyle: 'grouped' }],
        tags: ['s15', 'existing-firearms', 'gap'],
      },
    ],
  },
  {
    sectionId: 'S9',
    sectionKey: 'needJustification',
    templates: [
      {
        id: 's15.s9.core.001',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: 'I require the firearm applied for in order to pursue the lawful purpose described in this application in a practical, suitable, and responsible manner.',
        tags: ['s15', 'need', 'practical'],
        conditions: [{ field: 'needSummary', operator: 'falsy' }],
      },
      {
        id: 's15.s9.core.002',
        sectionId: 'S9',
        sectionKey: 'needJustification',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${needSummary}',
        variables: ['needSummary'],
        tags: ['s15', 'need', 'user-fact'],
      },
    ],
  },
  {
    sectionId: 'S10',
    sectionKey: 'suitabilityFit',
    templates: [
      {
        id: 's15.s10.core.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${firearmDescription} is suitable for the purpose for which it is required and is an appropriate firearm for that use.',
        variables: ['firearmDescription'],
        tags: ['s15', 'suitability', 'platform'],
        conditions: [{ field: 'suitabilitySummary', operator: 'falsy' }],
      },
      {
        id: 's15.s10.core.002',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'coreClaim',
        strength: 'veryStrong',
        text: '${suitabilitySummary}',
        variables: ['suitabilitySummary'],
        tags: ['s15', 'suitability', 'user-fact'],
      },
      {
        id: 's15.s10.support.001',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${capabilitySummary}',
        variables: ['capabilitySummary'],
        conditions: [{ field: 'capabilitySummary', operator: 'truthy' }],
        tags: ['s15', 'suitability', 'comparison', 'profile'],
      },
      {
        id: 's15.s10.support.002',
        sectionId: 'S10',
        sectionKey: 'suitabilityFit',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'Its characteristics make it a suitable and practical choice for the intended purpose described above.',
        conditions: [{ field: 'capabilitySummary', operator: 'falsy' }],
        tags: ['s15', 'suitability', 'comparison'],
      },
    ],
  },
  {
    sectionId: 'S11',
    sectionKey: 'activityUseDetail',
    templates: [
      {
        id: 's15.s11.intro.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'My actual and intended use of the firearm is relevant to this application and is summarised below.',
        tags: ['s15', 'activity'],
      },
      {
        id: 's15.s11.core.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'coreClaim',
        strength: 'strong',
        text: '${activitySummary}',
        variables: ['activitySummary'],
        conditions: [{ field: 'activitySummary', operator: 'truthy' }],
        tags: ['s15', 'activity', 'summary'],
      },
      {
        id: 's15.s11.support.001',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${huntingContextSummary}',
        variables: ['huntingContextSummary'],
        conditions: [{ field: 'huntingContextSummary', operator: 'truthy' }],
        tags: ['s15', 'activity', 'hunting'],
      },
      {
        id: 's15.s11.support.002',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${sportContextSummary}',
        variables: ['sportContextSummary'],
        conditions: [{ field: 'sportContextSummary', operator: 'truthy' }],
        tags: ['s15', 'activity', 'sport'],
      },
      {
        id: 's15.s11.support.003',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${participationFrequencySummary}',
        variables: ['participationFrequencySummary'],
        conditions: [{ field: 'participationFrequencySummary', operator: 'truthy' }],
        tags: ['s15', 'activity', 'frequency'],
      },
      {
        id: 's15.s11.support.004',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${huntingEnvironmentSummary}',
        variables: ['huntingEnvironmentSummary'],
        conditions: [{ field: 'huntingEnvironmentSummary', operator: 'truthy' }],
        tags: ['s15', 'activity', 'environment'],
      },
      {
        id: 's15.s11.support.005',
        sectionId: 'S11',
        sectionKey: 'activityUseDetail',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${sportDisciplineSummary}',
        variables: ['sportDisciplineSummary'],
        conditions: [{ field: 'sportDisciplineSummary', operator: 'truthy' }],
        tags: ['s15', 'activity', 'discipline'],
      },
    ],
  },
  {
    sectionId: 'S12',
    sectionKey: 'firearmCalibreContext',
    templates: [
      {
        id: 's15.s12.intro.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'sectionIntro',
        strength: 'standard',
        text: 'The firearm and calibre selected for this application are relevant to its intended use.',
        tags: ['s15', 'technical'],
      },
      {
        id: 's15.s12.core.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'coreClaim',
        strength: 'strong',
        text: 'The combination of firearm type, action, and calibre is suitable for the purpose for which the firearm is required.',
        tags: ['s15', 'technical', 'fit'],
      },
      {
        id: 's15.s12.support.001',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${illustrativeUseSummary}',
        variables: ['illustrativeUseSummary'],
        conditions: [{ field: 'illustrativeUseSummary', operator: 'truthy' }],
        tags: ['s15', 'technical', 'calibre', 'profile'],
      },
      {
        id: 's15.s12.support.002',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: '${capabilityLimitationSummary}',
        variables: ['capabilityLimitationSummary'],
        conditions: [{ field: 'capabilityLimitationSummary', operator: 'truthy' }],
        tags: ['s15', 'technical', 'limitation', 'profile'],
      },
      {
        id: 's15.s12.support.003',
        sectionId: 'S12',
        sectionKey: 'firearmCalibreContext',
        kind: 'supportingClaim',
        strength: 'strong',
        text: 'In the context of the intended use, the selected platform and calibre are reasonable, appropriate, and justified.',
        conditions: [
          { field: 'illustrativeUseSummary', operator: 'falsy' },
          { field: 'capabilityLimitationSummary', operator: 'falsy' },
        ],
        tags: ['s15', 'technical', 'calibre'],
      },
    ],
  },
  {
    sectionId: 'S15',
    sectionKey: 'conclusionRequest',
    templates: [
      {
        id: 's15.s15.conclusion.001',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'veryStrong',
        text: 'For the reasons set out above, I respectfully submit that this application is lawful, properly motivated, and should be approved.',
        tags: ['s15', 'conclusion', 'approval'],
      },
      {
        id: 's15.s15.conclusion.002',
        sectionId: 'S15',
        sectionKey: 'conclusionRequest',
        kind: 'conclusion',
        strength: 'strong',
        text: 'The application is supported by the applicant’s lawful intended use and the suitability of the firearm for that purpose.',
        tags: ['s15', 'conclusion', 'support'],
      },
    ],
  },
];

export const S15_SENTENCE_BANK: MotivationSentenceBank = {
  version: 'v1',
  sections: s15Sections,
};
