import type { TourStep } from '@/features/tour/types';

export const HOME_TOUR_STEPS: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Cinlo',
    body: 'Cinlo helps you quickly pick award-nominated films. This quick tour only takes a couple of minutes.',
    placement: 'auto',
  },
  {
    id: 'global-search-aliens',
    title: 'Search by title',
    body: 'Type \"aliens\" to narrow the list by movie title.',
    targetId: 'global-search-input',
    placement: 'bottom',
  },
  {
    id: 'movie-basic-info',
    title: 'Film basics',
    body: 'Each card shows core film details like year, director, genres, and cast.',
    targetId: 'movie-card-basic-info',
    placement: 'bottom',
  },
  {
    id: 'watch-plus',
    title: 'Track watch count',
    body: 'Tap + to record a watch for this film.',
    targetId: 'movie-watch-plus',
    placement: 'bottom',
  },
  {
    id: 'expand-card',
    title: 'Open movie details',
    body: 'Tap the movie title row (left side) to expand this movie card.',
    targetId: 'movie-expand-toggle',
    placement: 'bottom',
  },
  {
    id: 'award-pill-colors',
    title: 'Read award results',
    body: 'Inside this section, green pills are wins and orange pills are nominations.',
    targetId: 'movie-awards-panel',
    placement: 'top',
  },
  {
    id: 'reset-current-filters',
    title: 'Reset before continuing',
    body: 'Tap Reset to clear the current filters.',
    targetId: 'reset-filters-button',
    placement: 'top',
  },
  {
    id: 'select-general-filter',
    title: 'Open General filter',
    body: 'Tap General to open award body, result, and watched filters.',
    targetId: 'filter-pill-general',
    placement: 'bottom',
  },
  {
    id: 'general-select-oscars-winner',
    title: 'Filter by body and result',
    body: 'In General, select the Oscars pill under "Award body" and the Winner pill under "Result".',
    targetId: 'general-filter-panel',
    placement: 'bottom',
  },
  {
    id: 'general-results-count',
    title: 'See filtered results',
    body: 'This row shows how many films remain after your filter is applied.',
    targetId: 'results-summary-row',
    placement: 'top',
  },
  {
    id: 'general-clear-filter',
    title: 'Clear this filter',
    body: 'Tap Clear this filter to remove the General filter selections.',
    targetId: 'general-clear-filter-button',
    placement: 'bottom',
  },
  {
    id: 'scroll-filter-pills',
    title: 'More filters to the right',
    body: 'Swipe this row horizontally to reveal more filter pills.',
    targetId: 'filter-pill-row',
    placement: 'bottom',
  },
  {
    id: 'tour-complete',
    title: 'Tour complete',
    body: 'Congratulations! You have completed the welcome tour. You can replay it from Settings whenever you want.\n\nYou can resume this tour any time from the Settings screen.',
    targetId: 'settings-gear-button',
    placement: 'bottom',
  },
];
