import { spacing } from '@/foundation/theme/spacing';

export const componentMetrics = {
  tabBar: {
    height: 72,
    horizontalMargin: spacing.none,
    bottomGap: spacing.md,
    borderRadius: spacing.none,
    horizontalPadding: spacing.lg,
    verticalPadding: spacing.sm,
    sideItemMinWidth: 72,
    sideIconSize: 24,
    centerButtonSize: 72,
    centerIconSize: 30,
    centerButtonLift: 18,
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffsetWidth: 0,
    shadowOffsetHeight: 2,
    elevation: 6,
    contentBottomClearance: spacing.none,
  },
  actionCard: {
    minHeight: 80,
    borderWidth: 1,
    borderRadius: 20,
    horizontalPadding: spacing.lg,
    verticalPadding: spacing.sm,
    contentGap: spacing.sm,
    actionsTopPadding: spacing.none,
    actionsGap: spacing.sm,
  },
  button: {
    size: {
      sm: 32,
      md: 40,
      lg: 48,
    },
    horizontalPadding: spacing.lg,
    verticalPadding: spacing.md,
  },
  roundIconButton: {
    size: {
      sm: 32,
      md: 40,
      lg: 48,
    },
    borderWidth: 1,
    floating: {
      shadowOpacity: 0.1,
      shadowRadius: 3,
      shadowOffsetWidth: 0,
      shadowOffsetHeight: 1,
      elevation: 2,
    },
  },
  chip: {
    minHeight: 30,
    horizontalPadding: spacing.md,
    verticalPadding: spacing.sm,
  },
  divider: {
    thickness: 1,
    spacing: {
      none: spacing.none,
      sm: spacing.sm,
      md: spacing.md,
      lg: spacing.lg,
    },
  },
  modal: {
    contentPaddingHorizontal: spacing['2xl'],
    contentPaddingVertical: spacing.lg,
  },
  passcodePad: {
    keySize: 68,
    dotSize: 14,
    dotBorderWidth: 2,
    dotGap: spacing.md,
    gridGap: 18,
    rowGap: spacing.xl,
    keyContentMinHeight: 38,
    dotRadius: 7,
    keyPressedOpacity: 0.8,
    keyDisabledOpacity: 0.5,
    sectionGap: spacing.lg,
    dotsMarginTop: spacing.md,
  },
  authPinScreen: {
    copyGap: spacing.md,
    footerPaddingVertical: spacing.md,
    footerActionsTopPadding: spacing.lg,
    footerActionsMaxWidth: 240,
  },
} as const;
