import { spacing } from '@/theme/spacing';

export const componentMetrics = {
  button: {
    minHeight: 52,
    minWidth: 52,
    horizontalPadding: spacing.lg,
    verticalPadding: spacing.md,
    contentGap: 10,
    sublabelMarginTop: 2,
    disabledOpacity: 0.5,
  },
  iconButton: {
    sizes: {
      xs: 32,
      sm: 36,
      md: 44,
      lg: 52,
    },
    labelledHorizontalPadding: 14,
    labelledVerticalPadding: 12,
    bottomLabelHorizontalPadding: 12,
    bottomLabelVerticalPadding: 10,
    bottomLabelMinWidthOffset: 18,
    bottomLabelMinHeightOffset: 34,
    contentGap: 6,
  },
  chip: {
    minHeight: 30,
    horizontalPadding: spacing.md,
    verticalPadding: spacing.sm,
    contentGap: spacing.sm,
    iconSize: 16,
    disabledOpacity: 0.55,
    pressedOpacity: 0.88,
  },
  passcodePad: {
    keySize: 68,
    dotSize: 14,
    dotBorderWidth: 2,
    dotGap: spacing.md,
    gridGap: 18,
    rowGap: spacing.xl,
    keyContentMinHeight: 38,
    sideInset: 20,
    dotRadius: 7,
    keyPressedOpacity: 0.8,
    keyDisabledOpacity: 0.5,
  },
  tabs: {
    baseHeight: 58,
    androidHeightOffset: 10,
    androidPaddingTop: 10,
    iosPaddingTop: 6,
    androidPaddingBottomOffset: 12,
    androidMinPaddingBottom: 18,
    iosPaddingBottomOffset: -2,
    iosMinPaddingBottom: 6,
    borderWidth: 1,
  },
  modal: {
    iosSheetMarginTop: 32,
    androidSheetMarginTop: 12,
    headerPaddingHorizontal: spacing['2xl'],
    headerPaddingTop: spacing['2xl'],
    headerPaddingBottom: spacing.lg,
    contentPaddingHorizontal: spacing['2xl'],
    contentPaddingVertical: spacing.lg,
    footerPaddingHorizontal: spacing['2xl'],
    footerPaddingVertical: spacing.lg,
  },
  documentCard: {
    padding: spacing.lg,
    gap: spacing.md,
    titleRightGap: spacing.sm,
    actionRowMarginTop: spacing.md,
    actionRowPaddingTop: spacing.md,
    actionRowGap: spacing.xl,
    actionItemGap: spacing.sm,
    titlePaddingRight: spacing.sm,
    pillHorizontalPadding: 10,
    pillVerticalPadding: 5,
    pillFontSize: 11,
  },
  reminderCard: {
    padding: spacing.lg,
    gap: spacing.sm,
    titleGap: spacing.sm,
  },
  statusBanner: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    gap: spacing.sm,
    listGap: 10,
    itemGap: spacing.sm,
    pressedOpacity: 0.96,
    bulletSize: 16,
  },
  issueSummary: {
    pressedOpacity: 0.96,
    subtitleGap: spacing.xs,
    actionsGap: spacing.md,
  },
  actionList: {
    itemGap: spacing.md,
  },
  summaryRow: {
    wrapperMarginBottom: spacing.lg,
    labelGap: spacing.sm - 2,
    pressableMinHeight: 56,
    pressableHorizontalPadding: spacing.lg,
    pressableVerticalPadding: spacing.md,
    valueGap: spacing.sm,
    multilineChevronMarginLeft: spacing.sm,
    pressedOpacity: 0.92,
    disabledOpacity: 0.5,
    chevronSize: 20,
  },
  settings: {
    themeChipMinWidth: 84,
    themeChipPressedOpacity: 0.92,
    rowGap: spacing.lg,
    rowPaddingVertical: spacing.md,
    rowCopyGap: spacing.xs,
    rowDividerWidth: 1,
  },
} as const;
